import '../constants/app_constants.dart';

/// A decoded ArtVault QR code.
class QrPayload {
  final String paintingId;
  final String? title;
  final String? artistName;
  final double? price;
  final String? currency;
  final String? description;
  final String? imageUrl;

  const QrPayload({
    required this.paintingId,
    this.title,
    this.artistName,
    this.price,
    this.currency,
    this.description,
    this.imageUrl,
  });

  /// True when the code carries none of the metadata fields — i.e. it was
  /// generated by an older ArtVault build that only embedded the local id.
  bool get isLegacy =>
      title == null &&
      artistName == null &&
      price == null &&
      currency == null &&
      description == null &&
      imageUrl == null;
}

/// Builds QR payloads for artworks and parses scanned codes back.
///
/// The code carries the painting's local id plus its title/artist and, when
/// available, price, currency, a short description and a remote image URL.
/// The id is device-local, so the metadata lets scanners on *other* devices
/// find the artwork (or offer to add it) instead of showing
/// "Painting not found".
abstract final class QrService {
  /// Longest description embedded in a code — keeps the QR dense enough to
  /// scan reliably from a phone screen.
  static const int maxDescriptionChars = 140;

  /// Canonical deep link stored in every artwork QR code.
  static String payloadFor(
    String paintingId, {
    String? title,
    String? artistName,
    double? price,
    String? currency,
    String? description,
    String? imageUrl,
  }) {
    final sb = StringBuffer(
      '${AppConstants.deepLinkScheme}://artwork/$paintingId',
    );
    final params = <String>[];
    if (title != null && title.isNotEmpty) {
      params.add('t=${Uri.encodeQueryComponent(title)}');
    }
    if (artistName != null && artistName.isNotEmpty) {
      params.add('a=${Uri.encodeQueryComponent(artistName)}');
    }
    if (price != null && price > 0) {
      params.add('p=${price.toStringAsFixed(2)}');
    }
    if (currency != null && currency.isNotEmpty) {
      params.add('c=${Uri.encodeQueryComponent(currency)}');
    }
    if (description != null && description.isNotEmpty) {
      final trimmed = description.replaceAll(RegExp(r'\s+'), ' ').trim();
      final short = trimmed.length > maxDescriptionChars
          ? '${trimmed.substring(0, maxDescriptionChars)}…'
          : trimmed;
      params.add('d=${Uri.encodeQueryComponent(short)}');
    }
    if (imageUrl != null && imageUrl.isNotEmpty) {
      // Only remote URLs travel in the code — local file paths are
      // meaningless on another device.
      if (imageUrl.startsWith('http://') || imageUrl.startsWith('https://')) {
        params.add('i=${Uri.encodeQueryComponent(imageUrl)}');
      }
    }
    if (params.isNotEmpty) sb.write('?${params.join('&')}');
    return sb.toString();
  }

  /// Parses a scanned payload. Returns null for foreign codes so the
  /// scanner can ignore unrelated QR codes.
  static QrPayload? parsePayload(String raw) {
    final trimmed = raw.trim();
    final prefix = '${AppConstants.deepLinkScheme}://artwork/';
    if (trimmed.startsWith(prefix)) {
      final rest = trimmed.substring(prefix.length);
      final idPart = rest.split('?').first;
      if (idPart.isEmpty) return null;

      String? title;
      String? artistName;
      double? price;
      String? currency;
      String? description;
      String? imageUrl;
      final query = rest.contains('?') ? rest.split('?').last : '';
      for (final pair in query.split('&')) {
        if (pair.isEmpty) continue;
        final kv = pair.split('=');
        if (kv.length != 2) continue;
        final key = kv[0];
        final value = Uri.decodeQueryComponent(kv[1]);
        if (key == 't') title = value;
        if (key == 'a') artistName = value;
        if (key == 'p') price = double.tryParse(value);
        if (key == 'c') currency = value;
        if (key == 'd') description = value;
        if (key == 'i') imageUrl = value;
      }
      return QrPayload(
        paintingId: idPart,
        title: title,
        artistName: artistName,
        price: price,
        currency: currency,
        description: description,
        imageUrl: imageUrl,
      );
    }
    // Accept a bare id too (very old codes).
    if (RegExp(r'^[a-zA-Z0-9\-_]{8,}$').hasMatch(trimmed)) {
      return QrPayload(paintingId: trimmed);
    }
    return null;
  }

  /// Reads a painting id out of a scanned payload.
  static String? parsePaintingId(String raw) => parsePayload(raw)?.paintingId;
}
